<?php

namespace App\Helpers;

class PdfHelper
{
    /**
     * Get base64 encoded header image for PDF
     */
    public static function getHeaderImageBase64(): string
    {
        // Check if logo file exists and encode it
        $logoPath = public_path('images/logo.png');
        
        if (file_exists($logoPath)) {
            $imageData = file_get_contents($logoPath);
            return base64_encode($imageData);
        }
        
        // Return a simple SVG logo as base64 if no logo file exists
        $svgLogo = '<svg width="200" height="60" xmlns="http://www.w3.org/2000/svg">
            <rect width="200" height="60" fill="#009245"/>
            <text x="100" y="35" font-family="Arial, sans-serif" font-size="18" fill="white" text-anchor="middle" font-weight="bold">ShopSmart</text>
        </svg>';
        
        return base64_encode($svgLogo);
    }
    
    /**
     * Get company information for PDF header
     */
    public static function getCompanyInfo(): array
    {
        return [
            'name' => config('app.name', 'ShopSmart'),
            'address' => '123 Main Street, Dar es Salaam, Tanzania',
            'phone' => '+255 712 345 678',
            'email' => 'info@shopsmart.com',
            'website' => 'https://shopsmart.com',
        ];
    }
    
    /**
     * Get PDF footer text
     */
    public static function getFooterText(): string
    {
        $company = self::getCompanyInfo();
        return "Generated by {$company['name']} SMS Management System on " . now()->format('Y-m-d H:i:s');
    }
    
    /**
     * Format currency for PDF
     */
    public static function formatCurrency(float $amount): string
    {
        return 'TZS ' . number_format($amount, 2);
    }
    
    /**
     * Get page number text
     */
    public static function getPageNumberText(int $page, int $total): string
    {
        return "Page {$page} of {$total}";
    }
    
    /**
     * Get watermark text for PDF
     */
    public static function getWatermarkText(): string
    {
        return 'CONFIDENTIAL - ShopSmart SMS Logs';
    }
    
    /**
     * Get table headers for SMS logs PDF
     */
    public static function getSmsLogTableHeaders(): array
    {
        return [
            'Message ID',
            'Reference',
            'From',
            'To',
            'Message',
            'Status',
            'Sent At',
            'User',
        ];
    }
    
    /**
     * Get CSS styles for PDF
     */
    public static function getPdfStyles(): string
    {
        return '
            body {
                font-family: Arial, sans-serif;
                font-size: 12px;
                line-height: 1.4;
                color: #333;
            }
            .header {
                text-align: center;
                margin-bottom: 30px;
                border-bottom: 2px solid #009245;
                padding-bottom: 20px;
            }
            .header img {
                max-width: 200px;
                margin-bottom: 10px;
            }
            .header h1 {
                color: #009245;
                margin: 10px 0 5px 0;
                font-size: 24px;
            }
            .header p {
                color: #666;
                margin: 5px 0;
                font-size: 14px;
            }
            table {
                width: 100%;
                border-collapse: collapse;
                margin: 20px 0;
            }
            th, td {
                border: 1px solid #ddd;
                padding: 8px;
                text-align: left;
            }
            th {
                background-color: #009245;
                color: white;
                font-weight: bold;
            }
            tr:nth-child(even) {
                background-color: #f9f9f9;
            }
            .status-delivered {
                color: #28a745;
                font-weight: bold;
            }
            .status-pending {
                color: #ffc107;
                font-weight: bold;
            }
            .status-rejected {
                color: #dc3545;
                font-weight: bold;
            }
            .status-accepted {
                color: #007bff;
                font-weight: bold;
            }
            .footer {
                margin-top: 30px;
                text-align: center;
                color: #666;
                font-size: 10px;
                border-top: 1px solid #ddd;
                padding-top: 10px;
            }
        ';
    }
}
